# Azure deployment workflow

name: Stage this application

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request event but only for the "labeled" type
  pull_request:
    types: [ "labeled" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    if: contains(github.event.pull_request.labels.*.name, 'stage')


